### ISSUE TITLE
Springboot  + GlusterFS : Unable to build DLL from 'glusterfs-java-filesystem/tree/combined-with-libgfapi' on windows 10

### ISSUE THREAD

**Issue by dhsrik** [semiosis/glusterfs-java-filesystem#22]
Hi Team,

Greetings
We are unable to build the complete source as we see following errors during the build, we used the goal 'mvn package shade:shade' 
Kindly guide on how to proceed further with this issue.

Following updates were done on Win10 before ewe reached this step

1) MVS 2008 was installed to have vcbuild in place for eclipse
2) We tried to run manually via MVS2008 command prompt but we were stuck with sys/error.h file or directory not found

Not able to proceed further with considerable hours already spent on finding solution to this issue  

 --- maven-hawtjni-plugin:1.15:build (default) @ libgfapi-linux64 ---
[INFO] executing: cmd.exe /X /C "vcbuild /platform:x64 vs2008.vcproj release"
[INFO] Microsoft (R) Visual C++ Project Builder - Command Line Version 9.00.30729
[INFO] Copyright (C) Microsoft Corporation. All rights reserved.
[INFO] 
[INFO] Error: project file 'vs2008.vcproj' was not found or not a valid project file.
[INFO] Project file 'vs2008.vcproj' could not be loaded.
[INFO] The project is either missing from disk or access was denied.
[INFO] rc: -1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for glusterfs-java-filesystem-project 1.0.5-SNAPSHOT:
[INFO] 
[INFO] glusterfs-java-filesystem-project .................. SUCCESS [  0.472 s]
[INFO] libgfapi-jni ....................................... SUCCESS [  1.467 s]
[INFO] libgfapi-linux64 ................................... FAILURE [  0.352 s]
[INFO] glusterfs-java-filesystem .......................... SKIPPED
[INFO] glusterfs-java-filesystem-example .................. SKIPPED
[INFO] ------------------------------------------------------------------------

**Comment by louiszuckerman** [comment]
Hello, I'm sorry to say I can't be much help here. I have not maintained this project in many years.

However, at the time I was working on it, this project only worked on Linux (not Windows or Mac) because it required the glusterfs server & development symbol packages to be installed.

The error you posted appears to be caused by missing glusterfs C libraries, which would be provided by the glusterfs server pacakges on Linux.

There is some conversation in previous issues about this as well, most recently #20, so I suggest reading through those.

Good luck!

**Comment by dhsrik** [comment]
Hi @louiszuckerman ,

Thanks very much for your response. will try to look at alternate solution for our issue of having centralized location for flat file processing.

Regards,
Sridhar
